/* eslint-disable react-hooks/exhaustive-deps */
/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'
import Image from 'next/image'
import stylesBawaanNext from '../../styles/Home.module.css'
import PropTypes from 'prop-types';
import styles from './styles'
import { Card, Button } from '@mui/material';
import { useEffect } from 'react';

export default function ReduxExample(props) {
  
  useEffect(() => {
    props.actions.getPokemon()
  }, [])

  return (
    <div className={stylesBawaanNext.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={stylesBawaanNext.main}>
        <h1 className={stylesBawaanNext.title}>
          Welcome to <a href="https://redux.js.org/introduction/getting-started">Redux Example</a>
        </h1>

        <p className={stylesBawaanNext.description}>
          Get started by learnt{' '}
          <code className={stylesBawaanNext.code}>this example</code>
        </p>

        <div className={stylesBawaanNext.grid}>
          <a href="https://redux.js.org/introduction/getting-started" className={stylesBawaanNext.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Redux features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={stylesBawaanNext.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>
          <div css={styles.action}>
            <h3>Test Redux Here</h3>
            <div className="action-field">
              <Button className="increment" onClick={() => props.actions.incremented()}>increment</Button>
              <Button className="decrement" onClick={() => props.actions.decremented()}>decrement</Button>
              <span>
                = {props.value}
              </span>
            </div>
          </div>
          <div css={styles.pokemon}>
            {props.pokemon?.map((val, i) => (
              <Card className="card" key={i}>
                <h3>Redux Async Example</h3>
                <img src={val?.sprites?.front_shiny} alt={val?.name} layout="fill" />
                <div className="title">
                  {val?.name}
                </div>
              </Card>
            ))}
          </div>
        </div>
      </main>

      <footer className={stylesBawaanNext.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={stylesBawaanNext.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

// kalau mau nambah props untuk komponen bisa taro disini agar yang lain tau apa aja propsnya
ReduxExample.propTypes = {
  actions: PropTypes.object,
  value: PropTypes.number,
  pokemon: PropTypes.array,
}

ReduxExample.defaultProps = {
  actions: PropTypes.object,
  value: 0,
  pokemon: []
}